### ISSUE TITLE
Kasih Kredit nya

### ISSUE THREAD

**Issue by ruhend** [xIKRATOSx/Ikratos-MD-v1#3]
Im Yan Xiao Ya Kasih Di Kredit Nya broo Ini Base Elaina

**Comment by xIKRATOSx** [comment]
In Tqto plugin I gave you credits.
And now in readme too 💕
Your base had some issues 
I would love to contribute in your repo too💗

**Comment by xIKRATOSx** [comment]
Credits done 👌🏼✅
